// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDch3Wwm4JtiT8UTGjkzORucZ2IcfosPac',
    appId: '1:597173933512:web:e70f4a6678b800b0e81cfd',
    messagingSenderId: '597173933512',
    projectId: 'real-math-d9ddf',
    authDomain: 'real-math-d9ddf.firebaseapp.com',
    storageBucket: 'real-math-d9ddf.firebasestorage.app',
    measurementId: 'G-L3SW3WX12K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOz0UiIyF-jQMd2c7-a8yiKXnd95pRCjw',
    appId: '1:597173933512:android:923333465527f58ae81cfd',
    messagingSenderId: '597173933512',
    projectId: 'real-math-d9ddf',
    storageBucket: 'real-math-d9ddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC11PV4rBztKfbyTMO9QhBMlEF-sJT65gQ',
    appId: '1:597173933512:ios:675bf7a9688fa0bfe81cfd',
    messagingSenderId: '597173933512',
    projectId: 'real-math-d9ddf',
    storageBucket: 'real-math-d9ddf.firebasestorage.app',
    iosBundleId: 'com.example.worldMath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC11PV4rBztKfbyTMO9QhBMlEF-sJT65gQ',
    appId: '1:597173933512:ios:675bf7a9688fa0bfe81cfd',
    messagingSenderId: '597173933512',
    projectId: 'real-math-d9ddf',
    storageBucket: 'real-math-d9ddf.firebasestorage.app',
    iosBundleId: 'com.example.worldMath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDch3Wwm4JtiT8UTGjkzORucZ2IcfosPac',
    appId: '1:597173933512:web:c8bdee2431a92075e81cfd',
    messagingSenderId: '597173933512',
    projectId: 'real-math-d9ddf',
    authDomain: 'real-math-d9ddf.firebaseapp.com',
    storageBucket: 'real-math-d9ddf.firebasestorage.app',
    measurementId: 'G-WTY1N5ZFQH',
  );

}